# 0. Imports

In [2]:
import json
import os
import pandas as pd

# 1. generate dataframe to hold results

In [9]:
path = "./data/regression_results/"
results_files = os.listdir(path)

#all_results = dict()
#df_list = []

cols = ['dep_var', 'policy', 'bins_list', 'bin', 'r_squared', 'p_value', 'param', 'std_err']
all_data = dict()
pk = 0
for r in results_files:
    if 'bins' not in r:
        continue
    dep_var = r.split('bins')[0][:-1]
#     print("r = ", r)
    bins_str = r.split('=')[1].split('.')[0]
    bins_list = [(int(e.split('-')[0]), int(e.split('-')[1]))
                  for e in bins_str.split('_')]
    with open(path+r, "r") as f:
        data = json.load(f)
        
    for policy in data:
        r2 = data[policy]['r_squared']
        
        for b in data[policy]['p_values']:
            all_data[pk] = {
                'dep_var': dep_var,
                'bins_list': str(bins_list),
                'policy': policy,
                'bin': b,
                'rsquared': r2,
                'p_value': data[policy]['p_values'][b],
                'param': data[policy]['params'][b],
                'std_err': data[policy]['std_err'][b]
            }
            pk += 1
                
    df = pd.DataFrame.from_dict(all_data, orient='index')

In [10]:
df

,dep_var,bins_list,policy,bin,rsquared,p_value,param,std_err
0,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",outdoor and recreation - stop - county,const,0.000026,0.000000e+00,0.430151,0.000771
1,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",outdoor and recreation - stop - county,0-14,0.000026,1.130057e-06,0.294389,0.060480
2,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",outdoor and recreation - stop - county,15-28,0.000026,6.960655e-09,0.362587,0.062602
3,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",outdoor and recreation - stop - county,29-999,0.000026,5.084651e-01,0.006996,0.010581
4,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",non-essential businesses - stop - state,const,0.014947,0.000000e+00,0.215626,0.001469
...,...,...,...,...,...,...,...,...
1395,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",construction - start - county,29-999,0.000028,2.567499e-06,3.476225,0.739197
1396,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",executive order - start - state,const,0.000950,0.000000e+00,24.313962,0.023222
1397,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",executive order - start - state,0-14,0.000950,1.445569e-72,-19.999720,1.110036
1398,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",executive order - start - state,15-28,0.000950,8.304991e-54,-17.745101,1.148980
1399,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",executive order - start - state,29-999,0.000950,0.000000e+00,7.408221,0.188141

In [12]:
df.sort_values(by='rsquared', ascending=False)

,dep_var,bins_list,policy,bin,rsquared,p_value,param,std_err
1295,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",childcare - start - state,29-999,0.090656,0.000000e+00,26.525747,0.060435
1292,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",childcare - start - state,const,0.090656,0.000000e+00,2.877087,0.055765
1293,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",childcare - start - state,0-14,0.090656,1.328923e-06,0.691492,0.143006
1294,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",childcare - start - state,15-28,0.090656,4.353505e-02,-0.296071,0.146676
1258,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",entertainment - stop - state,15-28,0.089630,1.396683e-21,1.368581,0.143421
...,...,...,...,...,...,...,...,...
556,new_deaths_1e6,"[(0, 14), (15, 999)]",personal care - stop - county,15-999,0.000001,1.080018e-01,-0.102967,0.064064
555,new_deaths_1e6,"[(0, 14), (15, 999)]",personal care - stop - county,0-14,0.000001,4.484749e-01,-0.300007,0.395808
509,new_deaths_1e6,"[(0, 14), (15, 999)]",entertainment - stop - county,const,0.000001,0.000000e+00,0.435382,0.001785
510,new_deaths_1e6,"[(0, 14), (15, 999)]",entertainment - stop - county,0-14,0.000001,2.577822e-01,0.137159,0.121203
511,new_deaths_1e6,"[(0, 14), (15, 999)]",entertainment - stop - county,15-999,0.000001,2.983866e-01,-0.021927,0.021085

In [13]:
df.sort_values(by='p_value')

,dep_var,bins_list,policy,bin,rsquared,p_value,param,std_err
0,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",outdoor and recreation - stop - county,const,0.000026,0.000000,0.430151,0.000771
712,new_deaths_7day_1e6,"[(0, 14), (15, 999)]",manufacturing - start - state,15-999,0.004908,0.000000,0.160863,0.001570
713,new_deaths_7day_1e6,"[(0, 14), (15, 999)]",mask mandate - start - county,const,0.000391,0.000000,0.425582,0.000786
716,new_deaths_7day_1e6,"[(0, 14), (15, 999)]",entertainment - start - county,const,0.000028,0.000000,0.431434,0.000789
719,new_deaths_7day_1e6,"[(0, 14), (15, 999)]",childcare - start - state,const,0.018559,0.000000,0.078748,0.001954
...,...,...,...,...,...,...,...,...
817,new_deaths_1e6,"[(0, 14), (15, 28), (29, 999)]",gyms - stop - state,0-14,0.004093,0.973991,0.000432,0.013257
513,new_deaths_1e6,"[(0, 14), (15, 999)]",gyms - stop - state,0-14,0.003726,0.973996,0.000432,0.013259
803,new_deaths_1e6,"[(0, 14), (15, 28), (29, 999)]",outdoor and recreation - stop - county,29-999,0.000005,0.974887,-0.000771,0.024484
90,new_deaths_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",entertainment - start - county,15-28,0.000028,0.978412,-0.000533,0.019711
1275,new_cases_7day_1e6,"[(0, 14), (15, 28), (29, 999)]",personal care - stop - county,29-999,0.000009,0.990113,0.010414,0.840387

# 2. Visualize results

In [ ]:
def show_heatmap(df, dep_var, bins_list):
    data = df[df['dep_var']==dep_var and df['bins_list']==bins_list]