# Model set 1

Began training on 5-12

In [29]:
import covid_data as cd

In [30]:
df, df2 = cd.retrieve_data(load_local=False)
df, df2 = cd.clean_data(df, df2)
proc_policy_data = cd.prep_policy_data(df2, min_samples=10)

KeyError: 'location_name'

In [28]:
df

,uid,location_type,fips_code,location_name,state,date,total_population,cumulative_cases,cumulative_cases_per_100_000,cumulative_deaths,cumulative_deaths_per_100_000,new_cases,new_deaths,new_cases_per_100_000,new_deaths_per_100_000,new_cases_7_day_rolling_avg,new_deaths_7_day_rolling_avg
0,63072001,county,72001.0,Adjuntas,Puerto Rico,2020-01-22,18181.0,0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,63072001,county,72001.0,Adjuntas,Puerto Rico,2020-01-23,18181.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,63072001,county,72001.0,Adjuntas,Puerto Rico,2020-01-24,18181.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,63072001,county,72001.0,Adjuntas,Puerto Rico,2020-01-25,18181.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,63072001,county,72001.0,Adjuntas,Puerto Rico,2020-01-26,18181.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588883,84099999,special_exception,99999.0,NaN,Grand Princess,2021-05-07,NaN,103,NaN,3,NaN,0.0,0.0,NaN,NaN,0.0,0.0
1588884,84099999,special_exception,99999.0,NaN,Grand Princess,2021-05-08,NaN,103,NaN,3,NaN,0.0,0.0,NaN,NaN,0.0,0.0
1588885,84099999,special_exception,99999.0,NaN,Grand Princess,2021-05-09,NaN,103,NaN,3,NaN,0.0,0.0,NaN,NaN,0.0,0.0
1588886,84099999,special_exception,99999.0,NaN,Grand Princess,2021-05-10,NaN,103,NaN,3,NaN,0.0,0.0,NaN,NaN,0.0,0.0
1588887,84099999,special_exception,99999.0,NaN,Grand Princess,2021-05-11,NaN,103,NaN,3,NaN,0.0,0.0,NaN,NaN,0.0,0.0